import type { Proposal } from './types';

export const danielReyes: Proposal = {
  slug: 'DanielReyes',
  clientName: 'Psicología Clínica Chile',
  projectTitle: 'Psicología Clínica Chile',
  subtitle: '2026',
  startDate: 'Marzo 2026',
  duration: '6 meses',
  coverLabel: 'Plan de Marketing Digital',
  meta: [
    { label: 'Cliente', value: 'Psicología Clínica Chile' },
    { label: 'Inicio', value: 'Marzo 2026' },
    { label: 'Duración', value: '6 meses' },
    { label: 'Estado', value: '— Sin iniciar' },
  ],

  diagnostico: {
    sectionNumber: '01 — Diagnóstico',
    title: 'El sitio no está roto.\nSimplemente no trabaja.',
    intro: 'El Dr. Daniel Reyes tiene las credenciales más fuertes del mercado: PhD Universidad de Chile, 20 años de experiencia, consultor internacional. Nada de eso aparece en el primer scroll. En cambio, el hero dice "Excelencia clínica en psicoterapia" — una frase que podría usar cualquier centro del país sin cambiar una letra.',
    callout: {
      variant: 'amber',
      title: 'Diagnóstico inicial · Puntaje 4/10',
      text: 'El activo más valioso está escondido a dos clics. Sin precios, sin agendamiento online, sin Google Business Profile. El sitio tiene los ingredientes para funcionar bien, pero los usa pésimamente.',
    },
    scorecard: [
      { dimension: 'Propuesta de valor', score: '3/10', color: 'red', note: '"Excelencia clínica" no diferencia nada. Las credenciales del Dr. Reyes son el activo real y están ocultas.' },
      { dimension: 'CTA / Conversión', score: '3/10', color: 'red', note: 'Solo WhatsApp. Sin calendario, sin urgencia, sin incentivo. Máxima fricción para el paso más difícil.' },
      { dimension: 'Diferenciación', score: '2/10', color: 'red', note: 'PhD UChile + 20 años no aparecen en el primer scroll. El único diferenciador real está invisible.' },
      { dimension: 'Precio / Acceso', score: '1/10', color: 'red', note: 'Cero información de tarifas. "¿Cuánto cuesta un psicólogo Santiago?" es la búsqueda más frecuente.' },
      { dimension: 'Credibilidad / Confianza', score: '5/10', color: 'amber', note: '17 testimonios son el punto más fuerte. Sin fotos reales, sin Google Reviews, sin precios.' },
      { dimension: 'SEO / Contenido', score: '5/10', color: 'amber', note: 'Dominio joven (2025) = autoridad mínima. Las FAQ ayudan. Sin blog ni backlinks. Invisible en búsquedas clave.' },
      { dimension: 'Diseño / UX', score: '6/10', color: 'green', note: 'Limpio y legible. Sin jerarquía visual para conversión. Mejorable sin rediseño completo.' },
      { dimension: 'Mobile / Velocidad', score: '6/10', color: 'green', note: 'WordPress responsivo funcional. Sin optimización activa de Core Web Vitals.' },
    ],
    assets: [
      { type: '⭐ Principal', typeColor: 'teal', description: 'Dr. Daniel Reyes Pace — PhD UChile, 20 años, consultor internacional. LinkedIn thought leadership + cara de todos los videos + hero del nuevo sitio.' },
      { type: '17 testimonios', description: 'Video-testimonials para Instagram Reels + carrusel en Meta Ads + landing page.' },
      { type: '6 Isapres', description: 'Página /tarifas dedicada + keywords: \'psicólogo Banmédica\', \'Colmena\', \'Consalud\', etc.' },
      { type: 'Terapia Sexual', description: 'Diferenciador único del mercado. Contenido educativo en LinkedIn + campaña Meta específica.' },
      { type: 'Dual presencia', description: 'Presencial Ñuñoa + Online nacional. Google Ads local + Meta Ads segmentado por zona.' },
    ],
  },

  canales: {
    sectionNumber: '02 — Estrategia de Canales',
    title: 'Google Ads primero.\nMeta y LinkedIn, a evaluar.',
    intro: 'El plan parte con Google Ads como canal principal: captura intención de búsqueda directa desde el mes 1. La landing page + Fidelidapp son el hub de conversión. Meta Ads y LinkedIn se evalúan en Fase 3 solo si los resultados de Google Ads justifican escalar o diversificar.',
    channels: [
      {
        name: 'Google Ads — Canal Principal (Fase 1–2)',
        subtitle: 'Captura de intención de búsqueda · Long-tail estratégico · Activo desde el mes 1',
        headerColor: '#1B3A5C',
        keywords: [
          { text: 'psicólogo online Chile', priority: 'high' },
          { text: 'psicólogo Ñuñoa', priority: 'high' },
          { text: 'terapia de pareja Santiago', priority: 'high' },
          { text: 'psicólogo ansiedad Santiago', priority: 'medium' },
          { text: 'terapia sexual Santiago', priority: 'medium' },
          { text: 'psicólogo Banmédica', priority: 'medium' },
          { text: 'psicólogo Colmena / Consalud', priority: 'medium' },
          { text: 'psicólogo PhD Santiago', priority: 'long' },
          { text: 'Dr. en psicología Santiago', priority: 'long' },
        ],
      },
      {
        name: 'Landing Page + Fidelidapp — Hub de Conversión (Fase 1)',
        subtitle: 'Nuevo dominio · Hero con credenciales · Precios visibles · Calendly · Captura automática de leads',
        headerColor: '#276645',
        profiles: [
          { type: 'Dominio', typeColor: 'teal', description: 'Nuevo dominio más corto y recordable. Sin menú distractor. Hero con PhD UChile + 20 años en el primer scroll.' },
          { type: 'Conversión', typeColor: 'teal', description: 'Precios visibles + Calendly embebido + formulario de contacto. Eliminar dependencia total del WhatsApp.' },
          { type: 'Fidelidapp', typeColor: 'teal', description: 'Cada lead del formulario entra automáticamente al panel de Fidelidapp. Gestión, seguimiento y métricas de conversión centralizadas.' },
        ],
        pillars: [
          { num: 1, name: 'Hero con credenciales', objective: 'PhD UChile visible en primer scroll' },
          { num: 2, name: 'Precios visibles', objective: 'Reducir fricción de consulta' },
          { num: 3, name: 'Calendly integrado', objective: 'Agendar sin pasar por WhatsApp' },
          { num: 4, name: 'Formulario + Fidelidapp', objective: 'Captura automática de leads' },
          { num: 5, name: 'Testimonios', objective: 'Prueba social en la landing' },
          { num: 6, name: 'SEO on-page básico', objective: 'Tráfico orgánico complementario' },
        ],
      },
      {
        name: 'Meta Ads — Motor Complementario (Fase 3 · A Evaluar)',
        subtitle: 'Instagram + Facebook · Solo se activa si Google Ads muestra CPL > $15.000 o volumen insuficiente',
        headerColor: '#1E7D68',
        audiences: [
          { type: 'Principal', description: 'M+H 28–45 · Santiago RM · Intereses: psicología, bienestar mental, ansiedad, desarrollo personal' },
          { type: 'Pareja', description: 'Parejas 30–50 · Santiago + online Chile · Intereses: relaciones de pareja, matrimonio' },
          { type: 'Profesionales', description: 'Profesionales 25–45 · Todo Chile · Comportamiento: ejecutivos, viajeros frecuentes' },
          { type: 'Retargeting', description: 'Visitantes sitio 30 días + engagers IG que no agendaron' },
          { type: 'Lookalike 2%', description: 'Similar a quienes completaron formulario Fidelidapp (activar solo en Fase 3)' },
        ],
      },
      {
        name: 'LinkedIn — Autoridad y Referidos (Fase 3 · A Evaluar)',
        subtitle: 'Posicionamiento del Dr. Daniel Reyes como referente nacional · Posterior a validar Google Ads',
        headerColor: '#2A6099',
        profiles: [
          { type: 'Crítico', typeColor: 'red', description: 'Dr. Daniel Reyes — Headline con keywords, \'Acerca de\' optimizado, foto profesional, banner de marca. El activo principal cuando se active Fase 3.' },
          { type: 'Alta', typeColor: 'amber', description: 'Fernando — Arreglar enlace roto. Completar experiencia y foto actualizada.' },
          { type: 'Media', typeColor: 'amber', description: 'Allison + Página empresa — Crear o completar perfiles. Logo, banner, descripción con keywords.' },
        ],
        pillars: [
          { num: 1, name: 'Educación clínica', objective: 'Posicionar como experto' },
          { num: 2, name: 'Autoridad académica', objective: 'Diferenciación por trayectoria' },
          { num: 3, name: 'Salud mental laboral', objective: 'Atraer corporativos' },
          { num: 4, name: 'Desmitificación', objective: 'Reducir barrera de entrada' },
          { num: 5, name: 'Detrás del consultorio', objective: 'Humanizar y generar curiosidad' },
          { num: 6, name: 'CTA suave (1 de 5 posts)', objective: 'Conversión directa' },
        ],
      },
    ],
  },

  contenido: {
    sectionNumber: '03 — Sesión de Contenido',
    title: 'Medio día.\nCuatro meses de material.',
    intro: 'La sesión de contenido es la inversión de mayor apalancamiento del plan. Sin fotos y videos reales de Daniel y el equipo, ninguna campaña funciona bien en salud mental. En psicología, el paciente elige a su terapeuta antes de conocerlo — lo hace con el instinto.',
    callout: {
      variant: 'teal',
      title: 'Principio rector',
      text: 'Autenticidad sobre producción. Naturalidad sobre perfección. Calidez sobre corporativismo. Un video de Daniel hablando directo a cámara convierte más que cualquier rediseño gráfico.',
    },
    scripts: [
      {
        label: 'Video 1 · Presentación · 60–90 seg · Hero del sitio, LinkedIn, Meta Ads',
        labelColor: '#34d399',
        borderColor: '#34d399',
        quote: '"Hola, soy Daniel Reyes. Soy Doctor en Psicología de la Universidad de Chile y llevo más de 20 años acompañando a personas que quieren entender lo que les pasa y cambiar lo que no les funciona.\n\nEl primer paso siempre es el más difícil. Si estás listo, agenda tu primera consulta abajo."',
      },
      {
        label: 'Video 2 · ¿Cuándo buscar ayuda? · 60 seg · Instagram Reels, Meta Ads awareness',
        labelColor: '#2175a1',
        borderColor: '#2175a1',
        quote: '"Hay una pregunta que me hacen mucho: ¿cómo sé si lo que siento necesita ayuda profesional? Mi respuesta es directa: si lo estás preguntando, probablemente ya lo sabes."',
      },
      {
        label: 'Video 3 · Terapia de pareja · 45–60 seg · Meta Ads campaña pareja',
        labelColor: '#2A6099',
        borderColor: '#2A6099',
        quote: '"Las parejas que llegan a terapia no llegan rotas. Llegan antes de romperse. La terapia de pareja no es el último recurso. Es una inversión en lo que más importa."',
      },
      {
        label: 'Video 4 · Online para todo Chile · 30 seg · Meta Ads, Stories',
        labelColor: '#fbbf24',
        borderColor: '#fbbf24',
        quote: '"Si no estás en Santiago, no es excusa para no tener acceso a psicoterapia de calidad. Trabajo online con personas en todo Chile: desde Arica a Punta Arenas."',
      },
      {
        label: 'Video 5 · Terapia sexual · 60 seg · LinkedIn, Instagram educativo',
        labelColor: '#4ade80',
        borderColor: '#4ade80',
        quote: '"La terapia sexológica sigue siendo uno de los grandes tabúes en salud mental. Y eso tiene un costo enorme: personas que sufren en silencio durante años por problemas que tienen solución concreta."',
      },
    ],
    assets: [
      { type: 'Fotos Daniel', quantity: '5–8', destination: 'LinkedIn, web, Meta Ads, tarjeta digital' },
      { type: 'Fotos Equipo', quantity: '4–6', destination: 'Web /equipo, LinkedIn Fernando y Allison' },
      { type: 'Fotos Consultorio', quantity: '5–8', destination: 'Google Business Profile, web, Instagram' },
      { type: 'Reels editados', quantity: '5', destination: 'Instagram, LinkedIn video, Meta Ads, hero sitio' },
      { type: 'B-roll / Stories', quantity: '8–10', destination: 'Stories, Reels de apoyo con texto superpuesto' },
      { type: 'Total ~ 3–4 meses', quantity: '30–40', destination: 'piezas editadas listas para todos los canales', highlight: true, highlightColor: 'teal' },
    ],
  },

  phases: [
    {
      id: 1,
      anchorId: 'fase1',
      title: 'Fase 1 · Mes 1',
      subtitle: 'Setup, producción de contenido y lanzamiento. La infraestructura mínima necesaria para que Google Ads genere retorno real desde el primer día.',
      color: '#1B3A5C',
      sessions: [],
      tasks: [
        { id: '1_0', title: 'TALLER 1 — Kickoff estratégico', description: 'Definir propuesta de valor, precios, mensajes clave y brief para sitio y sesión de contenido', responsible: 'Consultor', week: 'S1', isConsulting: true },
        { id: '1_1', title: 'Revisar propuesta de diseño de Landing Page', description: 'Revisión de la propuesta de diseño para la nueva landing page. Definir estructura, mensajes clave y elementos de conversión.', responsible: 'Agencia', week: 'S1–S3', isConsulting: false },
        { id: '1_2', title: 'Integración Fidelidapp para captura de leads', description: 'El formulario de la landing envía leads directamente a la API de Fidelidapp. Cada consulta queda registrada automáticamente en el panel de gestión de contactos.', responsible: 'Agencia', week: 'S1–S2', isConsulting: false },
        { id: '1_3', title: 'Revisar y Mejorar Google Business Profile', description: 'Revisar la ficha existente de Google Business Profile. Optimizar fotos, descripción con keywords, horarios e isapres. Solicitar primeras reseñas.', responsible: 'Agencia', week: 'S1', isConsulting: false },
        { id: '1_4', title: 'Instalar Google Tag Manager + conversiones Google Ads', description: 'Configurar conversiones: vista /tarifas, clic agendar, formulario enviado, llamada telefónica.', responsible: 'Agencia', week: 'S1', isConsulting: false },
        { id: '1_5', title: 'SESIÓN DE FOTOS Y VIDEOS', description: 'Ejecutar plan completo sección 03. Medio día en el consultorio de Alonso de Ercilla.', responsible: 'Ag. + Equipo', week: 'S2', isConsulting: false },
        { id: '1_6', title: 'Edición fotos y videos', description: 'Entregar 5 reels editados + 15–20 fotos seleccionadas + material de historias.', responsible: 'Agencia', week: 'S3', isConsulting: false },
        { id: '1_7', title: 'Configurar Google Ads (search long-tail)', description: '8–10 keywords prioritarias. Anuncio con credenciales + CTA agendar. Conversiones conectadas a GTM.', responsible: 'Agencia', week: 'S3–S4', isConsulting: false },
        { id: '1_8', title: 'Lanzar nueva landing page con Google Ads activo', description: 'Activar campaña Google Ads apuntando al nuevo dominio. Verificar tracking de conversiones end-to-end.', responsible: 'Agencia', week: 'S4', isConsulting: false },
      ],
      milestones: [
        { title: 'Kickoff workshop completado', description: 'Propuesta de valor, mensajes clave y brief creativo definidos', relatedTasks: ['1_0'] },
        { title: 'Propuesta de diseño de Landing Page revisada', description: 'Propuesta de diseño revisada con estructura, mensajes clave y elementos de conversión definidos. Integración con Fidelidapp confirmada.', relatedTasks: ['1_1', '1_2'] },
        { title: 'Google Business Profile revisado y mejorado', description: 'Ficha existente optimizada con fotos, horarios, descripción con keywords e isapres. Primeras reseñas solicitadas.', relatedTasks: ['1_3'] },
        { title: 'Sesión de fotos/videos ejecutada', description: 'Banco de contenido generado (30–40 piezas editadas)', relatedTasks: ['1_5', '1_6'] },
        { title: 'Google Ads lanzado', description: 'Campañas search activas con tracking de conversiones y leads entrando a Fidelidapp', relatedTasks: ['1_7', '1_8'] },
      ],
      budget: {
        items: [
          { label: 'Relanzamiento landing page + nuevo dominio', sublabel: 'Diseño + desarrollo + dominio anual + integración Fidelidapp', amount: '$300.000', isHighlight: true },
          { label: 'Fotografía y videografía profesional (sesión)', sublabel: 'Medio día en consultorio · 5 Reels + 15–20 fotos', amount: '$150.000' },
          { label: 'Edición de fotos y videos (15–20 piezas)', sublabel: 'Reels editados + fotos retocadas + stories', amount: '$100.000' },
          { label: 'Configuración Google Ads + GTM + conversiones', sublabel: 'Setup inicial, estructura de campaña y tracking completo', amount: '$100.000' },
          { label: 'Setup técnico (Calendly, GBP, SEO on-page básico)', sublabel: 'Agendamiento online, ficha Google, optimización básica', amount: '$150.000' },
        ],
        consultingItems: [
          { label: 'Taller 1 · Kickoff estratégico', sublabel: '3 horas · incluido', amount: '$0' },
        ],
        total: '$800.000 CLP',
        totalLabel: 'Total Fase 1 · 50% adelantado ($400.000) + 50% al cierre ($400.000)',
      },
    },
    {
      id: 2,
      anchorId: 'fase2',
      title: 'Fase 2 · Meses 2–3',
      subtitle: 'Operación Google Ads. Gestión activa de campañas, optimización de keywords y mejora continua del CAC. Los leads capturados se registran automáticamente en Fidelidapp.',
      color: '#1E7D68',
      sessions: [
        { type: 'Sesión 4', hours: '2 horas', price: '$0', title: 'Revisión semana 3: primeros resultados Google Ads', description: 'Analizar las primeras 3 semanas de Google Ads. Identificar keywords con menor CPL. Ajustar bids, negativos y copy de anuncios.' },
        { type: 'Taller 2', hours: '2 horas', price: '$0', title: 'Mid-check estratégico mes 3', description: 'Revisar el funnel completo (tráfico → lead → paciente). Ajustar landing basado en datos reales. Evaluar si escalar presupuesto Google Ads o activar Fase 3.' },
      ],
      tasks: [
        { id: '2_0', title: 'Inversión Google Ads mes 2', description: '$200.000 CLP de pauta en Google Ads. Keywords long-tail priorizadas: psicólogo Ñuñoa, psicólogo online Chile, terapia de pareja Santiago, isapres.', responsible: 'Cliente + Agencia', week: 'Mes 2', isConsulting: false },
        { id: '2_1', title: 'Optimización semanal de Google Ads', description: 'Revisar search terms, agregar negativos, ajustar bids por keyword, pausar anuncios con CTR bajo. Reportería semanal.', responsible: 'Agencia', week: 'Mes 2–3', isConsulting: false },
        { id: '2_2', title: 'SESIÓN 4 — Revisión primeros resultados Google Ads', description: 'Semana 3 del mes 2. Analizar CPL, CTR, keywords ganadoras. Ajustar estructura de campaña.', responsible: 'Consultor', week: 'Mes 2', isConsulting: true },
        { id: '2_3', title: 'Solicitar reseñas Google activamente', description: 'Link directo a GBP por WhatsApp a pacientes satisfechos. Meta: 10 reseñas en 60 días.', responsible: 'Cliente', week: 'Mes 2', isConsulting: false },
        { id: '2_4', title: 'A/B test copy de anuncios Google Ads', description: '2 variantes de título y descripción. Pausar el anuncio con CTR más bajo. Escalar el que convierte.', responsible: 'Agencia', week: 'Mes 2–3', isConsulting: false },
        { id: '2_5', title: 'Inversión Google Ads mes 3', description: '$200.000 CLP de pauta. Si CPL < $12.000, escalar presupuesto hasta $300.000.', responsible: 'Cliente + Agencia', week: 'Mes 3', isConsulting: false },
        { id: '2_6', title: 'TALLER 2 — Mid-check estratégico', description: 'Revisar funnel completo, ajustar landing, decidir si activar Fase 3 (Meta + LinkedIn).', responsible: 'Consultor', week: 'Mes 3', isConsulting: true },
      ],
      milestones: [
        { title: 'Google Ads operando con inversión activa', description: '$200.000 CLP/mes en pauta. Keywords long-tail priorizadas activas', relatedTasks: ['2_0', '2_5'] },
        { title: 'CPL < $12.000 CLP', description: 'Costo por lead Google Ads por debajo del umbral objetivo', relatedTasks: ['2_1', '2_4'] },
        { title: '10+ reseñas Google', description: 'Protocolo de solicitud activo con pacientes satisfechos', relatedTasks: ['2_3'] },
        { title: 'Mid-check estratégico completado', description: 'Decisión informada sobre escalar Google Ads o activar Fase 3', relatedTasks: ['2_6'] },
      ],
      budget: {
        items: [
          { label: 'Inversión Google Ads (pauta mensual)', sublabel: '$200.000/mes · search long-tail · keywords priorizadas', amount: '$200.000/mes', isHighlight: true },
          { label: 'Gestión y optimización de campañas Google Ads', sublabel: 'Optimización semanal, reportería y A/B test de anuncios', amount: 'A convenir' },
        ],
        consultingItems: [
          { label: 'Sesión 4 · Revisión Google Ads · 2 horas', amount: '$0' },
          { label: 'Taller 2 · Mid-check estratégico · 2 horas', amount: '$0' },
        ],
        total: '$200.000 CLP/mes',
        totalLabel: 'Inversión mínima Fase 2 · Solo Google Ads',
      },
    },
    {
      id: 3,
      anchorId: 'fase3',
      title: 'Fase 3 · Meses 4–6 · A Evaluar',
      subtitle: 'Meta Ads + LinkedIn — posterior, a evaluar. Esta fase se activa solo si los resultados de Google Ads justifican escalar o si se buscan canales adicionales de captación.',
      color: '#276645',
      sessions: [
        { type: 'Sesión 5', hours: '2 horas', price: '$0', title: 'Evaluación: ¿activar Meta Ads?', description: 'Con datos de 2–3 meses de Google Ads, analizar si Meta Ads complementa o compite. Definir budget, audiencias y creativos de prueba.' },
        { type: 'Sesión 6', hours: '2 horas', price: '$0', title: 'Revisión resultados Meta Ads mes 1', description: 'Identificar el ad set con menor CPL. Ajustar targeting, creativos y copy. Comparar CPL Meta vs Google.' },
        { type: 'Taller 3', hours: '3 horas', price: '$0', title: 'Revisión trimestral completa', description: 'Presentación formal de resultados: CAC, ROAS, leads, pacientes captados. Recomendaciones para el siguiente ciclo. Handover estratégico al equipo.' },
      ],
      tasks: [
        { id: '3_0', title: 'Lanzar campaña Meta Lead Gen (evaluación previa)', description: '3 ad sets: Individual, Pareja, Profesionales. 2 creativos mínimo por ad set. Solo activar si Google Ads muestra CPL > $15.000 o volumen insuficiente.', responsible: 'Agencia', week: 'Mes 4', isConsulting: false },
        { id: '3_1', title: 'Activar retargeting Meta', description: 'Visitantes sitio 30 días + engagers IG. Creativo con urgencia leve. Leads capturados vía Fidelidapp.', responsible: 'Agencia', week: 'Mes 4', isConsulting: false },
        { id: '3_2', title: 'SESIÓN 5 — Evaluación activar Meta Ads', description: 'Revisar datos Google Ads. Decidir si Meta Ads suma o es prematuro. Definir estrategia y creativos.', responsible: 'Consultor', week: 'Mes 4', isConsulting: true },
        { id: '3_3', title: 'Escalar Meta Ads en ad set ganador', description: 'Aumentar presupuesto 20–30%. Activar Lookalike 2% basado en leads Fidelidapp.', responsible: 'Agencia', week: 'Mes 5', isConsulting: false },
        { id: '3_4', title: 'Activar campaña LinkedIn Ads (corporativo)', description: 'Lead Gen para RRHH y bienestar organizacional. Presupuesto: $100.000/mes. Solo activar si ticket promedio corporativo justifica el CPL mayor de LinkedIn.', responsible: 'Agencia', week: 'Mes 5–6', isConsulting: false },
        { id: '3_5', title: 'SESIÓN 6 — Revisión resultados Meta Ads', description: 'Identificar ad set ganador, ajustar, comparar CPL Meta vs Google. Decisión de mix de canales.', responsible: 'Consultor', week: 'Mes 5', isConsulting: true },
        { id: '3_6', title: 'Campaña de reseñas Google sistemática', description: 'Protocolo post-sesión: link + mensaje personalizado. Meta: 25 reseñas 5 estrellas.', responsible: 'Cliente + Ag.', week: 'Mes 4', isConsulting: false },
        { id: '3_7', title: 'Test contenido orgánico LinkedIn + Instagram', description: 'Evaluar si el material de la sesión fotográfica justifica un ritmo orgánico sostenible. Primeros 4–6 posts con material real.', responsible: 'Ag. + Daniel', week: 'Mes 4–5', isConsulting: false },
        { id: '3_8', title: 'TALLER 3 — Revisión trimestral completa', description: 'Presentación de resultados: CAC, ROAS, leads, pacientes captados. Handover estratégico.', responsible: 'Consultor', week: 'Mes 6', isConsulting: true },
      ],
      milestones: [
        { title: 'Decisión Meta Ads basada en datos', description: 'Evaluación formal con datos de Google Ads para activar o postergar Meta Ads', relatedTasks: ['3_2'] },
        { title: 'Meta Ads + retargeting activos (si se activa)', description: 'Campañas lead gen y retargeting Meta con leads capturados vía Fidelidapp', relatedTasks: ['3_0', '3_1', '3_3'] },
        { title: 'LinkedIn Ads corporativo (si se activa)', description: 'Campaña de lead gen para RRHH y bienestar organizacional', relatedTasks: ['3_4'] },
        { title: 'Revisión trimestral completa', description: 'Presentación de CAC, ROAS, leads y pacientes. Handover estratégico', relatedTasks: ['3_8'] },
      ],
      budget: {
        items: [
          { label: 'Meta Ads (Lead Gen + Retargeting)', sublabel: 'A evaluar · Motor complementario a Google Ads', amount: 'A evaluar' },
          { label: 'Google Ads (continuar)', sublabel: 'Mantener o escalar según CPL', amount: '$200.000+/mes' },
          { label: 'LinkedIn Ads (test corporativo)', sublabel: 'Solo si ticket corporativo justifica el CPL', amount: 'A evaluar' },
          { label: 'Gestión y optimización multi-canal', amount: 'A convenir' },
        ],
        consultingItems: [
          { label: 'Sesión 5 · Evaluación Meta Ads · 2h', amount: '$0' },
          { label: 'Sesión 6 · Revisión Meta Ads · 2h', amount: '$0' },
          { label: 'Taller 3 · Revisión trimestral · 3h', amount: '$0' },
        ],
        total: 'A evaluar',
        totalLabel: 'Total Fase 3 · Presupuesto definido según resultados Fase 2',
      },
    },
  ],

  resumen: {
    sectionNumber: '05 — Resumen',
    title: 'Un mes de setup.\nLuego, leads desde Google.',
    totals: [
      { label: 'Fase 1 · Setup completo', value: '$800K', sub: 'CLP · pago 50/50' },
      { label: 'Fase 2 · Google Ads mensual', value: '$200K', sub: 'CLP/mes · inversión en pauta', color: 'teal' },
      { label: 'Fase 3 · Meta + LinkedIn', value: 'A evaluar', sub: 'posterior, según resultados', color: 'violet' },
    ],
    summaryRows: [
      { phase: 'F1', phaseColor: '#1B3A5C', period: 'Mes 1', focus: 'Landing page + dominio + sesión fotos/videos + Google Ads setup + Fidelidapp', totalCLP: '$800.000', consulting: '$0', leads: 'Sin ads activos' },
      { phase: 'F2', phaseColor: '#1E7D68', period: 'Meses 2–3', focus: 'Google Ads operando · gestión + optimización + leads a Fidelidapp', totalCLP: '$200.000/mes', consulting: '$0', leads: '10–25/mes' },
      { phase: 'F3', phaseColor: '#276645', period: 'Meses 4–6', focus: 'Meta Ads + LinkedIn Ads · a evaluar según resultados Fase 2', totalCLP: 'A evaluar', consulting: '$0', leads: 'A proyectar' },
    ],
    kpis: [
      { name: 'CPL Google Ads · Costo por Lead', values: [{ period: 'Mes 2', value: '< $12K' }, { period: 'Mes 4+', value: '< $8K', isTarget: true }], tool: 'Google Ads Manager' },
      { name: 'Conv. Lead → Paciente', values: [{ period: 'Mes 2', value: '> 15%' }, { period: 'Mes 4+', value: '> 25%', isTarget: true }], tool: 'Fidelidapp + Registro manual' },
      { name: 'Conv. Rate Landing', values: [{ period: 'Mes 2', value: '> 2%' }, { period: 'Mes 4+', value: '> 4%', isTarget: true }], tool: 'Google Analytics 4' },
      { name: 'Leads capturados en Fidelidapp', values: [{ period: 'Mes 2', value: '> 10' }, { period: 'Mes 4+', value: '> 25', isTarget: true }], tool: 'Fidelidapp Dashboard' },
      { name: 'Reseñas Google', values: [{ period: 'Mes 2', value: '> 10' }, { period: 'Mes 6', value: '> 25', isTarget: true }], tool: 'Google Business Profile' },
      { name: 'Tráfico orgánico/mes', values: [{ period: 'Mes 2', value: '> 200' }, { period: 'Mes 4+', value: '> 600', isTarget: true }], tool: 'GA4 + Search Console' },
    ],
  },

  errores: [
    { title: 'Activar Meta Ads antes de validar Google Ads', description: 'Meta Ads es Fase 3: se evalúa solo con datos reales de 2–3 meses de Google Ads. Activarlo antes sin baseline de CPL es dispersar el presupuesto.' },
    { title: 'No responder leads en menos de 1 hora', description: 'En salud mental la ventana de decisión es corta. Un lead sin respuesta en el día ya contactó a la competencia.' },
    { title: 'Publicar en LinkedIn en tono corporativo', description: 'Daniel debe hablar como Daniel, no como institución. El contenido de PR frío no funciona aquí. La autenticidad es el activo.' },
    { title: 'Invertir en ads sin Google Business Profile activo', description: 'El 60% de los usuarios busca reseñas en Google antes de contactar a un psicólogo. Sin ficha, los ads trabajan a medias.' },
    { title: 'Usar fotos de stock en el nuevo sitio', description: 'La sesión del mes 1 existe precisamente para esto. Las fotos de stock se identifican a distancia y erosionan la confianza.' },
    { title: 'Saltar la Fase 1 para "ahorrar tiempo"', description: 'El nuevo dominio, la landing, el pixel y el banco de contenido son la base de todo. Sin ellos, la Fase 2 nace coja.' },
  ],

  footerQuote: '"El mayor activo de Psicología Clínica Chile aún no tiene voz digital. Un Doctor en Psicología con 20 años de trayectoria que el mercado no conoce todavía."',
  footerMeta: 'Consultoría de Growth Marketing · Propuesta confidencial · Marzo 2026',
};
